default_stages: [commit, push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-merge-conflict
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.8.0'
    hooks:
    -   id: mypy
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
    - id: ruff
      args: ["--fix", "--config=pyproject.toml"]
    - id: ruff-format
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.3
    hooks:
    - id: nbqa-black
-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.8'
    hooks:
    - id: bandit
      args: ["-c", "pyproject.toml"]
      additional_dependencies: [".[toml]"]
-   repo: https://github.com/snakemake/snakefmt
    rev: 'v0.10.1'
    hooks:
    - id: snakefmt
